syntax = "proto3";

package headscale.v1;

import "google/api/annotations.proto";

import "apikey.proto";
import "auth.proto";
import "node.proto";
import "policy.proto";
import "preauthkey.proto";
import "user.proto";

service HeadscaleService {
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse) {
    option (google.api.http) = {
      post: "/api/v1/user"
      body: "*"
    };
  }
  rpc RenameUser(RenameUserRequest) returns (RenameUserResponse) {
    option (google.api.http) = {
      post: "/api/v1/user/{old_id}/rename/{new_name}"
    };
  }
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse) {
    option (google.api.http) = {
      delete: "/api/v1/user/{id}"
    };
  }
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {
    option (google.api.http) = {
      get: "/api/v1/user"
    };
  }

  rpc CreatePreAuthKey(CreatePreAuthKeyRequest) returns (CreatePreAuthKeyResponse) {
    option (google.api.http) = {
      post: "/api/v1/preauthkey"
      body: "*"
    };
  }
  rpc ExpirePreAuthKey(ExpirePreAuthKeyRequest) returns (ExpirePreAuthKeyResponse) {
    option (google.api.http) = {
      post: "/api/v1/preauthkey/expire"
      body: "*"
    };
  }
  rpc DeletePreAuthKey(DeletePreAuthKeyRequest) returns (DeletePreAuthKeyResponse) {
    option (google.api.http) = {
      delete: "/api/v1/preauthkey"
    };
  }
  rpc ListPreAuthKeys(ListPreAuthKeysRequest) returns (ListPreAuthKeysResponse) {
    option (google.api.http) = {
      get: "/api/v1/preauthkey"
    };
  }

  rpc DebugCreateNode(DebugCreateNodeRequest) returns (DebugCreateNodeResponse) {
    option (google.api.http) = {
      post: "/api/v1/debug/node"
      body: "*"
    };
  }
  rpc GetNode(GetNodeRequest) returns (GetNodeResponse) {
    option (google.api.http) = {
      get: "/api/v1/node/{node_id}"
    };
  }
  rpc SetTags(SetTagsRequest) returns (SetTagsResponse) {
    option (google.api.http) = {
      post: "/api/v1/node/{node_id}/tags"
      body: "*"
    };
  }
  rpc SetApprovedRoutes(SetApprovedRoutesRequest) returns (SetApprovedRoutesResponse) {
    option (google.api.http) = {
      post: "/api/v1/node/{node_id}/approve_routes"
      body: "*"
    };
  }
  rpc RegisterNode(RegisterNodeRequest) returns (RegisterNodeResponse) {
    option (google.api.http) = {
      post: "/api/v1/node/register"
    };
  }
  rpc DeleteNode(DeleteNodeRequest) returns (DeleteNodeResponse) {
    option (google.api.http) = {
      delete: "/api/v1/node/{node_id}"
    };
  }
  rpc ExpireNode(ExpireNodeRequest) returns (ExpireNodeResponse) {
    option (google.api.http) = {
      post: "/api/v1/node/{node_id}/expire"
    };
  }
  rpc RenameNode(RenameNodeRequest) returns (RenameNodeResponse) {
    option (google.api.http) = {
      post: "/api/v1/node/{node_id}/rename/{new_name}"
    };
  }
  rpc ListNodes(ListNodesRequest) returns (ListNodesResponse) {
    option (google.api.http) = {
      get: "/api/v1/node"
    };
  }
  rpc BackfillNodeIPs(BackfillNodeIPsRequest) returns (BackfillNodeIPsResponse) {
    option (google.api.http) = {
      post: "/api/v1/node/backfillips"
    };
  }

  rpc AuthRegister(AuthRegisterRequest) returns (AuthRegisterResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/register"
      body: "*"
    };
  }
  rpc AuthApprove(AuthApproveRequest) returns (AuthApproveResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/approve"
      body: "*"
    };
  }
  rpc AuthReject(AuthRejectRequest) returns (AuthRejectResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/reject"
      body: "*"
    };
  }

  rpc CreateApiKey(CreateApiKeyRequest) returns (CreateApiKeyResponse) {
    option (google.api.http) = {
      post: "/api/v1/apikey"
      body: "*"
    };
  }
  rpc ExpireApiKey(ExpireApiKeyRequest) returns (ExpireApiKeyResponse) {
    option (google.api.http) = {
      post: "/api/v1/apikey/expire"
      body: "*"
    };
  }
  rpc ListApiKeys(ListApiKeysRequest) returns (ListApiKeysResponse) {
    option (google.api.http) = {
      get: "/api/v1/apikey"
    };
  }
  rpc DeleteApiKey(DeleteApiKeyRequest) returns (DeleteApiKeyResponse) {
    option (google.api.http) = {
      delete: "/api/v1/apikey/{prefix}"
    };
  }

  rpc GetPolicy(GetPolicyRequest) returns (GetPolicyResponse) {
    option (google.api.http) = {
      get: "/api/v1/policy"
    };
  }
  rpc SetPolicy(SetPolicyRequest) returns (SetPolicyResponse) {
    option (google.api.http) = {
      put: "/api/v1/policy"
      body: "*"
    };
  }
  rpc CheckPolicy(CheckPolicyRequest) returns (CheckPolicyResponse) {
    option (google.api.http) = {
      post: "/api/v1/policy/check"
      body: "*"
    };
  }

  rpc Health(HealthRequest) returns (HealthResponse) {
    option (google.api.http) = {
      get: "/api/v1/health"
    };
  }
}

message HealthRequest {}

message HealthResponse {
  bool database_connectivity = 1;
}
