#!/usr/bin/env python3
"""Generate ignored Rust test stubs for current-head headscale-go backlog items."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from collections import defaultdict
from typing import Any


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
INVENTORY = REPO_ROOT / "docs" / "headscale-current-head-surface-inventory-2026-06-02.json"
OUT = REPO_ROOT / "headscale-api" / "tests" / "current_head_go_parity_pending.rs"


class GenerateError(Exception):
    pass


def relative(path: pathlib.Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def test_name(normalized_name: str) -> str:
    suffix = re.sub(r"[^a-z0-9_]", "_", normalized_name.lower())
    suffix = re.sub(r"_+", "_", suffix).strip("_")
    if not suffix:
        raise GenerateError("empty normalized backlog test name")
    return f"go_parity_pending_{suffix}"


def load_backlog() -> list[dict[str, Any]]:
    try:
        with INVENTORY.open(encoding="utf-8") as handle:
            document = json.load(handle)
    except json.JSONDecodeError as err:
        raise GenerateError(f"{relative(INVENTORY)} is not valid JSON: {err}") from err

    backlog = document.get("backlog")
    if not isinstance(backlog, list):
        raise GenerateError(f"{relative(INVENTORY)} is missing a backlog array")

    integration_backlog: list[dict[str, Any]] = []
    seen_names: set[str] = set()
    seen_functions: set[str] = set()
    for index, item in enumerate(backlog):
        if not isinstance(item, dict):
            raise GenerateError(f"{relative(INVENTORY)} backlog[{index}] must be an object")
        if item.get("category") != "integration_test":
            continue

        upstream = item.get("upstream")
        if not isinstance(upstream, dict):
            raise GenerateError(f"{relative(INVENTORY)} backlog[{index}] is missing upstream")

        name = upstream.get("name")
        normalized_name = upstream.get("normalized_name")
        source = upstream.get("source")
        reason = item.get("reason")
        for label, value in {
            "upstream.name": name,
            "upstream.normalized_name": normalized_name,
            "upstream.source": source,
            "reason": reason,
        }.items():
            if not isinstance(value, str) or not value:
                raise GenerateError(
                    f"{relative(INVENTORY)} backlog[{index}] is missing {label}"
                )

        fn_name = test_name(normalized_name)
        if name in seen_names:
            raise GenerateError(f"duplicate upstream backlog test {name!r}")
        if fn_name in seen_functions:
            raise GenerateError(f"duplicate generated Rust test {fn_name!r}")
        seen_names.add(name)
        seen_functions.add(fn_name)
        integration_backlog.append(item)

    return sorted(
        integration_backlog,
        key=lambda item: (
            str(item["upstream"]["source"]).split(":", 1)[0],
            str(item["upstream"]["source"]),
            str(item["upstream"]["name"]),
        ),
    )


def render(backlog: list[dict[str, Any]]) -> str:
    by_source_file: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in backlog:
        source_file = str(item["upstream"]["source"]).split(":", 1)[0]
        by_source_file[source_file].append(item)

    lines: list[str] = [
        "// Generated by scripts/generate_go_parity_backlog_stubs.py; do not edit by hand.",
        "// Each ignored test is an authorized current-head headscale-go parity surface.",
        "",
        f"const AUTHORIZED_PENDING_CURRENT_HEAD_GO_PARITY_TESTS: usize = {len(backlog)};",
        "",
        "#[test]",
        "fn current_head_go_parity_pending_authorization_count() {",
        f"    assert_eq!(AUTHORIZED_PENDING_CURRENT_HEAD_GO_PARITY_TESTS, {len(backlog)});",
        "}",
        "",
    ]

    if backlog:
        lines.extend(
            [
                "macro_rules! pending_current_head_go_parity {",
                "    ($name:ident, $upstream:literal, $source:literal, $reason:literal $(,)?) => {",
                "        #[test]",
                '        #[ignore = "pending current-head headscale-go parity implementation; authorized before execution"]',
                "        fn $name() {",
                "            panic!(",
                '                "pending current-head headscale-go parity test: {} at {} ({})",',
                "                $upstream, $source, $reason",
                "            );",
                "        }",
                "    };",
                "}",
                "",
            ]
        )

    for source_file in sorted(by_source_file):
        lines.append(f"// {source_file}")
        for item in by_source_file[source_file]:
            upstream = item["upstream"]
            lines.extend(
                [
                    "pending_current_head_go_parity!(",
                    f"    {test_name(str(upstream['normalized_name']))},",
                    f"    {rust_string(str(upstream['name']))},",
                    f"    {rust_string(str(upstream['source']))},",
                    f"    {rust_string(str(item['reason']))},",
                    ");",
                    "",
                ]
            )

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated stub file is not up to date",
    )
    args = parser.parse_args()

    try:
        rendered = render(load_backlog())
        if args.check:
            current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
            if current != rendered:
                print(f"{relative(OUT)} is out of date; run {relative(pathlib.Path(__file__))}", file=sys.stderr)
                return 1
            print(f"checked {relative(OUT)} current-head parity stubs")
            return 0

        OUT.write_text(rendered, encoding="utf-8")
        print(f"generated {relative(OUT)}")
    except GenerateError as err:
        print(err, file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
