#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

policy_json="${REAL_CLIENT_POLICY_JSON:-$(ruby -rjson -e 'puts JSON.pretty_generate({acls: [{action: "accept", src: ["*"], dst: ["*:*"]}]})')}"

REAL_CLIENT_WORKDIR="${REAL_CLIENT_WORKDIR:-target/real-client/postgres-user-node-lifecycle-restart-smoke}" \
REAL_CLIENT_ONLINE_LASTSEEN_TARGET=rust \
REAL_CLIENT_DATABASE_BACKEND=postgres \
REAL_CLIENT_CLIENT_COUNT="${REAL_CLIENT_CLIENT_COUNT:-3}" \
REAL_CLIENT_CLIENT_USERS="${REAL_CLIENT_CLIENT_USERS:-alice,bob,carol}" \
REAL_CLIENT_POLICY_JSON="${policy_json}" \
REAL_CLIENT_USER_NODE_LIFECYCLE_RESTART=true \
REAL_CLIENT_RENAME_USER_AFTER_LOGIN="${REAL_CLIENT_RENAME_USER_AFTER_LOGIN:-alice:alice-renamed}" \
REAL_CLIENT_EXPIRE_NODE_INDEX="${REAL_CLIENT_EXPIRE_NODE_INDEX:-2}" \
REAL_CLIENT_DELETE_NODE_INDEX="${REAL_CLIENT_DELETE_NODE_INDEX:-3}" \
REAL_CLIENT_DESTROY_USER_AFTER_NODE_DELETE="${REAL_CLIENT_DESTROY_USER_AFTER_NODE_DELETE:-carol}" \
REAL_CLIENT_EXPECT_USERS_AFTER_LIFECYCLE_RESTART="${REAL_CLIENT_EXPECT_USERS_AFTER_LIFECYCLE_RESTART:-alice-renamed,bob}" \
REAL_CLIENT_EXPECT_MACHINE_COUNT="${REAL_CLIENT_EXPECT_MACHINE_COUNT:-3}" \
REAL_CLIENT_TIMEOUT_SECS="${REAL_CLIENT_TIMEOUT_SECS:-300}" \
  tools/real-client/online-lastseen-common.sh
