#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

REAL_CLIENT_RESTART_TARGET=rust \
REAL_CLIENT_DATABASE_BACKEND=postgres \
REAL_CLIENT_RESTART_ROUTE_HEALTH=true \
REAL_CLIENT_RESTART_ROUTE_HEALTH_MIXED_EXIT=true \
REAL_CLIENT_RESTART_ROUTE_HEALTH_ALL_UNHEALTHY=true \
REAL_CLIENT_ROUTE_HEALTH_NO_RESTART=true \
REAL_CLIENT_WORKDIR="${REAL_CLIENT_WORKDIR:-target/real-client/postgres-route-health-mixed-exit-all-unhealthy-smoke}" \
REAL_CLIENT_TIMEOUT_SECS="${REAL_CLIENT_TIMEOUT_SECS:-320}" \
REAL_CLIENT_RESTART_ROUTE="${REAL_CLIENT_RESTART_ROUTE:-10.96.0.0/24}" \
REAL_CLIENT_RESTART_EXIT_ROUTES="${REAL_CLIENT_RESTART_EXIT_ROUTES:-0.0.0.0/0,::/0}" \
REAL_CLIENT_ROUTE_HEALTH_PROBE_INTERVAL_SECS="${REAL_CLIENT_ROUTE_HEALTH_PROBE_INTERVAL_SECS:-2}" \
REAL_CLIENT_ROUTE_HEALTH_PROBE_TIMEOUT_SECS="${REAL_CLIENT_ROUTE_HEALTH_PROBE_TIMEOUT_SECS:-1}" \
  tools/real-client/restart-persistence-common.sh
