#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

route="${REAL_CLIENT_ROUTE:-10.77.0.0/24}"

REAL_CLIENT_WORKDIR="${REAL_CLIENT_WORKDIR:-target/real-client/route-primary-sticky-smoke}" \
REAL_CLIENT_CLIENT_COUNT="${REAL_CLIENT_CLIENT_COUNT:-2}" \
REAL_CLIENT_ADVERTISE_ROUTES="${REAL_CLIENT_ADVERTISE_ROUTES:-${route}}" \
REAL_CLIENT_EXPECT_AVAILABLE_ROUTES="${REAL_CLIENT_EXPECT_AVAILABLE_ROUTES:-${route}}" \
REAL_CLIENT_APPROVE_ROUTES="${REAL_CLIENT_APPROVE_ROUTES:-${route}}" \
REAL_CLIENT_EXPECT_APPROVED_ROUTES="${REAL_CLIENT_EXPECT_APPROVED_ROUTES:-${route}}" \
REAL_CLIENT_EXPECT_PRIMARY_ROUTE="${REAL_CLIENT_EXPECT_PRIMARY_ROUTE:-${route}}" \
REAL_CLIENT_EXPECT_PRIMARY_FAILOVER_ROUTE="${REAL_CLIENT_EXPECT_PRIMARY_FAILOVER_ROUTE:-${route}}" \
REAL_CLIENT_EXPECT_PRIMARY_STICKY_ROUTE="${REAL_CLIENT_EXPECT_PRIMARY_STICKY_ROUTE:-${route}}" \
  tools/real-client/authkey-smoke.sh
