#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

REAL_CLIENT_WORKDIR="${REAL_CLIENT_WORKDIR:-target/real-client/test-derp-server-websocket-scenario-smoke}" \
REAL_CLIENT_FORCE_DERP_WEBSOCKET="${REAL_CLIENT_FORCE_DERP_WEBSOCKET:-true}" \
REAL_CLIENT_EXPECT_DERP_NATIVE_RAW_DENIED_MAX="${REAL_CLIENT_EXPECT_DERP_NATIVE_RAW_DENIED_MAX:-0}" \
REAL_CLIENT_EXPECT_DERP_NATIVE_WEBSOCKET_ALLOWED_MIN="${REAL_CLIENT_EXPECT_DERP_NATIVE_WEBSOCKET_ALLOWED_MIN:-2}" \
REAL_CLIENT_EXPECT_DERP_NATIVE_WEBSOCKET_DENIED_MAX="${REAL_CLIENT_EXPECT_DERP_NATIVE_WEBSOCKET_DENIED_MAX:-0}" \
  tools/real-client/postgres-derp-native-smoke.sh
