// Generated by scripts/generate_go_parity_backlog_stubs.py; do not edit by hand.
// Each ignored test is an authorized current-head headscale-go parity surface.

const AUTHORIZED_PENDING_CURRENT_HEAD_GO_PARITY_TESTS: usize = 0;

#[test]
fn current_head_go_parity_pending_authorization_count() {
    assert_eq!(AUTHORIZED_PENDING_CURRENT_HEAD_GO_PARITY_TESTS, 0);
}
